version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-inertia-app
    container_name: laravel-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: laravel
        MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql-data:
